# Nombre de la aplicacion
spring.application.name=StayGO

# Configuracion de conexion a Base de Datos en ALWAYSDATA
spring.datasource.url=jdbc:mysql://mysql-staygo.alwaysdata.net/staygo_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=staygo
spring.datasource.password=awardspace1

# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuracion de Thymeleaf
spring.thymeleaf.cache=false

# Forzar codificacion UTF-8 para los diccionarios de idiomas
spring.messages.encoding=UTF-8

#Idioma por defecto
spring.web.locale=es
server.forward-headers-strategy=framework